### ISSUE TITLE
ld: symbol(s) not found for architecture i386

### ISSUE THREAD

**Issue by hagile** [talko/soundtouch#1]
I'm getting following errors and I've tried applying all of the solutions available.

But still couldn't get rid of the errors

```
"soundtouch::BPMDetect::inputSamples(float const*, int)", referenced from:

-[MyClassName beatsFromAssetReader:channels:sampleRate:] in MyClassName.o

"soundtouch::BPMDetect::getBpm()", referenced from:

 -[MyClassName beatsFromAssetReader:channels:sampleRate:] in MyClassName.o

"soundtouch::BPMDetect::BPMDetect(int, int)", referenced from:

-[MyClassName beatsFromAssetReader:channels:sampleRate:] in MyClassName.o
```

> ld: symbol(s) not found for architecture i386

This is a too old project and not sure how to get rid out of these errors. What's going is – If I try to solve on error another error will popups and so on.

**Comment by enrimr** [comment]
I imagine you haven't compile for architecture i386. Try it with a real device first

**Comment by hagile** [comment]
@enrimr, Ok – how do I do that? I've not added `SoundTouch.framework` directly. Instead all files added in my project. Like this.

![screen shot 2015-09-03 at 6 05 32 pm](https://cloud.githubusercontent.com/assets/11436406/9658361/67f4965e-5266-11e5-8085-31268680ce58.png)

What should I do in this case?

As SoundTouch is not available via CocoaPods, I have added it manually. And all other libs or frameworks added through cocoapods.

**Comment by hagile** [comment]
Are there any steps to integrate SoundTouch in iOS project? @enrimr

**Comment by enrimr** [comment]
I have not here my iOS project where I compile soundtouch but the answer to your question is no, there isn't any public steps to follow. Tonight I will help you when I finished to work. I can share with you my compiled soundtouch library also

**Comment by hagile** [comment]
@enrimr, Ok this is "Sound"s good. I'll be waiting for your help. Thanks once again.

**Comment by rspeyer** [comment]
@hagile @enrimr is correct that we currently do not build the project for i386 - by default it only compiles for iOS devices (the Standard architectures list in XCode), not emulators or Mac.

It would be great to add support for the other architectures, and if you do get it working please submit a PR.

The "proper" way to include `SoundTouch`, or any other third-party project, is as follows:
1. Rather than adding the files within `SoundTouch` to your project, choose `SoundTouch.xcodeproj` and add that directly into your project. This ensures that when you do build you get all the proper build settings for `SoundTouch`
2. In your project, under "Build Phases", expand "Target Dependencies" and add `SoundTouch` using the "+" button
3. Expand "Link Binary with Libraries" and add `libSoundTouch.a` using the "+" button. Note that it will be red until you successfully build, but this is OK.

Once you have it properly integrated, you can try changing the Architectures list in `SoundTouch.xcodeproj` directly and see if it works.

Hope this helps.

**Comment by hagile** [comment]
@rspeyer, thank you so much for quick response, would you please let us know from where I can download full source code of `SoundTouch.xcodeproj` ?

**Comment by rspeyer** [comment]
@hagile it is included in this project - if you clone the full source of `talko/soundtouch` you should have it

**Comment by hagile** [comment]
Ok great, I just found that. Btw, should I need to add entire project (and everything) downloaded from above link?

**Comment by rspeyer** [comment]
If you add the `xcodeproj` everything else will be added automatically

**Comment by hagile** [comment]
@rspeyer , yes you're right.. but unfortunately, 2nd step is not working. I meant, I can't add soundtouch as my project target dependancy.

**Comment by hagile** [comment]
![screen shot 2015-09-03 at 6 34 43 pm](https://cloud.githubusercontent.com/assets/11436406/9658897/7f13d742-526a-11e5-8220-4a59b14698fe.png)

**Comment by rspeyer** [comment]
@hagile what architectures are you building your project for? Just i386? Maybe its not showing up because it doesn't have your architectures supported right now

**Comment by hagile** [comment]
![screen shot 2015-09-03 at 6 43 55 pm](https://cloud.githubusercontent.com/assets/11436406/9659091/c79a24de-526b-11e5-8955-b65785193f81.png)

This is my project target architecture. @rspeyer

**Comment by enrimr** [comment]
@hagile I have uploaded the compiled library to a repository https://github.com/enrimr/soundtouch-ios-library , hope this can help until you can finally compile by your own. I think @rspeyer have told you how to include SoundTouch.xcodeproj

**Comment by hagile** [comment]
@enrimr, that's awesome! thank you so much for this. I've just added the compiled lib and everything is now working. But now I'm getting an error inside code. I'm not sure what's is the issue?

**Comment by hagile** [comment]
Error code 

```
- (NSInteger)beatsFromAssetReader:(AVAssetReader *)assetReader channels:(NSNumber *)channels sampleRate:(NSNumber *)sampleRate
{
    CMSampleBufferRef buffer;
    soundtouch::BPMDetect *detector = new soundtouch::BPMDetect((int)[channels unsignedIntegerValue], (int)[sampleRate unsignedIntegerValue]);

    while ([assetReader status] == AVAssetReaderStatusReading) {
        buffer = [[assetReader.outputs lastObject] copyNextSampleBuffer];
        if (buffer != NULL) {
            size_t sampleSize = CMSampleBufferGetNumSamples(buffer);

            float samples[sampleSize];
            AudioBuffer audioBuffer = {
                .mNumberChannels = static_cast<UInt32>([channels unsignedIntegerValue]),
                .mDataByteSize = static_cast<UInt32>(sizeof(samples)),
                .mData = samples
            };
            AudioBufferList bufferList;
            bufferList.mNumberBuffers = 1;
            bufferList.mBuffers[0] = audioBuffer;

            CMBlockBufferRef blockBuffer;
            CMSampleBufferGetAudioBufferListWithRetainedBlockBuffer(buffer, NULL, &bufferList, sizeof(bufferList), NULL, NULL, 0, &blockBuffer);

            float *sampleData = (float *)bufferList.mBuffers[0].mData;
            detector->inputSamples(sampleData, sampleSize); //Error is here

            CFRelease(blockBuffer);
        }
    }

    NSInteger beats = floor(detector->getBpm());
    delete detector;

    return beats;
}
```

**Comment by hagile** [comment]
This is the error :

![screen shot 2015-09-03 at 7 31 03 pm](https://cloud.githubusercontent.com/assets/11436406/9660258/5afaaa68-5272-11e5-924c-702256fb9415.png)

@enrimr  @rspeyer 

Please help !!!

**Comment by rspeyer** [comment]
@hagile is this your code? It appears that you are using `float` samples, but `SoundTouch` is currently compiled to expect 16-bit integer samples.

Try changing the pre-processor macros to define `SOUNDTOUCH_FLOAT_SAMPLES` instead of `SOUNDTOUCH_INTEGER_SAMPLES`, so change your code to use integers.

**Comment by hagile** [comment]
@rspeyer, nope its not my code, I'm going to add some additional functionality into the project, nothing much. Please give me idea about where can I change this to get rid of this error. Thanks a ton!!

**Comment by hagile** [comment]
I think, @enrimr needs to rebuild the library?

**Comment by enrimr** [comment]
No, you have to use the right types, if the compiler said to you that you are using float where you need a short, you must use a short!
