### ISSUE TITLE
Is this strictly iOS or OS X as well?

### ISSUE THREAD

**Issue by mavavilj** [talko/soundtouch#2]
Is this strictly iOS or OS X as well?

**Comment by rspeyer** [comment]
@Mviljamaa I have not explicitly tested on OSX, but I think it should be rather straightforward to get it to work on OSX, and would be a great addition to the library.

Some other users have encountered some issues adding additional architectures (https://github.com/rspeyer/soundtouch/issues/1), but I think we should be able to overcome them. If you are willing to give OSX a shot let me know how it goes!
